#! /bin/bash
set -x

plat=gfortran.ubuntu

thisdir=$(pwd)

template=$thisdir/template.$plat

srcdir=$(dirname $thisdir)

FMS_UTILS=$srcdir/fms_shared_v5

FMS_UTILITIES="$FMS_UTILS/include $FMS_UTILS/platform $FMS_UTILS/constants $FMS_UTILS/fms $FMS_UTILS/time_manager $FMS_UTILS/mpp $FMS_UTILS/diag_manager  $FMS_UTILS/memutils"

MKMF=$thisdir/mkmf

mkdir -p $thisdir/exec

cd $thisdir/exec

$MKMF -m Makefile -p a.out -t $template -x $thisdir $FMS_UTILITIES  $FMS_UTILS/mpp/include
exit
